[project]
name = "dsml-indiviual-project"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "jupyterlab>=4.5.0",
    "numpy>=2.2.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
]
